/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/

const ICON_HOME            = "markers/icons8-favorite-location-100.png";
const ICON_SAFEHOUSE       = "markers/icons8-secure-location-100.png";
const ICON_VILLAGE         = "markers/icons8-people-square-location-100.png";
const ICON_EMPTY_VILLAGE   = "markers/icons8-square-location-100.png";
const ICON_UNKNOWN         = "markers/icons8-unknown-location-100.png";
const ICON_DEFAULT         = "markers/icons8-location-100.png";
const ICON_DEFAULT_DONE    = "markers/icons8-location-100-white-checked.png";
const ICON_EXAMINED        = "markers/icons8-checked-location-100.png";
const ICON_DANGER          = "markers/icons8-dangerous-location-100.png";
const ICON_MINE            = "markers/icons8-mine-location-100.png";
const ICON_WATCHOUT        = "markers/icons8-attention-location-100.png";
const ICON_LIGHTHOUSE      = "markers/icons8-lighthouse-100.png";
const ICON_MISC            = "markers/icons8-map-pin-100.png";
const ICON_PORTAL          = "markers/icons8-portal-100.png";
const ICON_SHIPWRECK       = "markers/icons8-anchor-100.png";
const ICON_SHIPWRECK_DONE  = "markers/icons8-anchor-100-white-checked.png";
const ICON_POT_SHIPWRECK   = "markers/icons8-unknown-anchor-100.png";
const ICON_TRAIL_RUIN      = "markers/icons8-trails-100.png";
const ICON_TRAIL_RUIN_DONE = "markers/icons8-trails-100-checked.png";
const ICON_SUBWAY          = "markers/icons8-subway-100.png";
const ICON_TRAIN           = "markers/icons8-trainstation-100.png";
const ICON_LIBRARY         = "markers/icons8-library-100.png";
const ICON_HOSTEL          = "markers/icons8-hostel-100.png";
const ICON_HORSE           = "markers/icons8-horse-100.png";

const IMAGE_SCALE = 0.3;
const IMAGE_SCALE_SMALL = 0.2;

const YOFFSET_2L = 15;
const YOFFSET = 10;

const MARKER_FONT = "12px Arial, Helvetica, sans-serif";

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        // ****************************************
        //
        // Home bases 
        //
        // ****************************************
        //tp 4302.5 125 2243.5
        {
            x: 4303,
            z: 2244,
            image: ICON_HOME,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Mellys\nFerienwohnung",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 455,
            z: -311,
            image: ICON_HOME,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Jaegerhausen",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 650,
            z: -450,
            image: ICON_HOME,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Rolands\nWohnpark",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET_2L,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Safehouses 
        //
        // ****************************************
        {
            x: 1186,
            z: 1756,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3678,
            z: 1915,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2251,
            z: 1822,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3334,
            z: 1819,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2827,
            z: 1864,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1903,
            z: 1830,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1592,
            z: 1816,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1384,
            z: -376,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -457,
            z: -969,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 831,
            z: 1194,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 748,
            z: -205,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 492,
            z: -522,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 1331,
            z: 253,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 828,
            z: -491,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 192,
            z: -453,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 647,
            z: -696,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 985,
            z: -875,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 765,
            z: 252,
            image: ICON_SAFEHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Safehouse",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Villages
        //
        // ****************************************
        {
            x: -5804,
            z: -5350,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -5812,
            z: -4763,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -5255,
            z: -4614,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 153,
            z: -4170,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 272,
            z: -4825,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 197,
            z: -5333,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 188,
            z: -5716,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1940,
            z: -5217,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1898,
            z: 2218,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 5612,
            z: 2901,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 4932,
            z: 2469,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 4565,
            z: 2421,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 4000,
            z: 1760,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2507,
            z: -3531,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2474,
            z: 4741,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -3129,
            z: 3401,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -4731,
            z: 1332,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1818,
            z: 4048,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -940,
            z: 3445,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -388,
            z: 2997,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3923,
            z: 588,
            image: ICON_EMPTY_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: 3500,
            z: 1115,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: 3308,
            z: 806,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: -3468,
            z: -2547,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: -235,
            z: -3156,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2947,
            z: -1971,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3516,
            z: -2474,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "black", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2923,
            z: -3004,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3075,
            z: -2523,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 268,
            z: 2891,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2444,
            z: 60,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1307,
            z: 1369,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 635,
            z: -2995,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1915,
            z: -1603,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 710,
            z: 634,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -271,
            z: -1967,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
    	{
            x: -965,
            z: -2437,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 310,
            z: -1951,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -818,
            z: -1420,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -815,
            z: -2064,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1099,
            z: -1003,
            image: ICON_EMPTY_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 732,
            z: 1682,
            image: ICON_VILLAGE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dorf",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Waldanwesen
        //
        // ****************************************
        {
            x: 5656,
            z: 1822,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Waldanwesen",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1753,
            z: -7229,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Waldanwesen",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        
        // ****************************************
        //
        // Trail ruins
        //
        // ****************************************
        {
            x: -5696,
            z: -4655,
            image: ICON_TRAIL_RUIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Trail Ruin",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2000,
            z: -4197,
            image: ICON_TRAIL_RUIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Trail Ruin",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2880,
            z: 1714,
            image: ICON_TRAIL_RUIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Trail Ruin",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3008,
            z: 1283,
            image: ICON_TRAIL_RUIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Trail Ruin",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
    
        // ****************************************
        //
        // Unknown places
        //
        // ****************************************
        {
            x: -861,
            z: -8483,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "???",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -316,
            z: -9137,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "???",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1451,
            z: -2123,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "???",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1245,
            z: -1891,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "???",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1507,
            z: -572,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "???",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -904,
            z: -2120,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "???",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1728,
            z: 68,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Antike Stadt",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Dschungeltempel
        //
        // ****************************************
        {
            x: 2279,
            z: -329,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dschungeltempel",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1862,
            z: -952,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Dschungeltempel",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
    
        // ****************************************
        //
        // Ozeanmonumente
        //
        // ****************************************
	    {
            x: 3864,
            z: -282,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 3209,
            z: -411,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 2152,
            z: -1336,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -2962,
            z: 1146,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1463,
            z: 213,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
		{
            x: -921,
            z: -697,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
		{
            x: -1304,
            z: -216,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -2280,
            z: -2840,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1346,
            z: -908,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 71,
            z: 200,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -314,
            z: -312,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -186,
            z: -840,
            image: ICON_DANGER,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanmonument",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
    
        // ****************************************
        //
        // Wüstentempel
        //
        // ****************************************
        {
            x: -198,
            z: -8934,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -821,
            z: 2810,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -341,
            z: -2181,
            image: ICON_EXAMINED,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 106,
            z: -1174,
            image: ICON_EXAMINED,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -821,
            z: 2810,
            image: ICON_EXAMINED,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -741,
            z: 3322,
            image: ICON_EXAMINED,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 602,
            z: -2518,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -502,
            z: -2005,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Wüstentempel",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Ozeanruinen
        //
        // ****************************************
        {
            x: -1817,
            z: 4955,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1593,
            z: -2536,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 73,
            z: 486,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1853,
            z: -7571,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1434,
            z: -3784,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1430,
            z: -4060,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1416,
            z: -2057,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2408,
            z: -3113,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1208,
            z: -2408,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3356,
            z: -153,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -782,
            z: 483,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -238,
            z: 717,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3847,
            z: 2647,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Ozeanruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        
        // ****************************************
        //
        // Shipwrecks 
        //
        // ****************************************
        {
            x: -5101,
            z: -3971,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -6876,
            z: -4573,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -3918,
            z: -4042,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1491,
            z: -8045,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2036,
            z: -2831,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1303,
            z: -2956,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1724,
            z: -2844,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 2916,
            z: -72,
            image: ICON_SHIPWRECK_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 3093,
            z: 57,
            image: ICON_SHIPWRECK_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 2981,
            z: 10,
            image: ICON_SHIPWRECK_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1904,
            z: -2388,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1617,
            z: 652,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -2188,
            z: 624,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2651,
            z: 4878,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1289,
            z: -1307,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 17,
            z: -1643,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2119,
            z: -1476,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2037,
            z: -1131,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -896,
            z: -373,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: -1654,
            z: 1450,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 32,
            z: 122,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 431,
            z: 571,
            image: ICON_SHIPWRECK_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },        
	    {
            x: 187,
            z: -1479,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -716,
            z: -311,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 97,
            z: -764,
            image: ICON_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -917,
            z: -1125,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1885,
            z: -268,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -267,
            z: 104,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -355,
            z: -109,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -568,
            z: 451,
            image: ICON_POT_SHIPWRECK,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Schiffswrack?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Minen 
        //
        // ****************************************
	    {
            x: -504,
            z: -1493,
            image: ICON_MINE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Mine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 471,
            z: -2410,
            image: ICON_MINE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Mine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Pillager Outposts 
        //
        // ****************************************
        {
            x: -4777,
            z: -4827,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 279,
            z: -5832,
            image: ICON_WATCHOUT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 5451,
            z: 3013,
            image: ICON_WATCHOUT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3239,
            z: -615,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -488,
            z: 3017,
            image: ICON_WATCHOUT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 391,
            z: -1112,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 617,
            z: -2342,
            image: ICON_DEFAULT_DONE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -681,
            z: -2009,
            image: ICON_WATCHOUT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Pillager Outpost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Portalruinen
        //
        // ****************************************
        {
            x: -5525,
            z: -5589,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -5124,
            z: -5627,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -6075,
            z: -5404,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -5490,
            z: -4994,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -6957,
            z: -4350,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -5636,
            z: -4156,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -5045,
            z: -4188,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 685,
            z: -924,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 156,
            z: -8917,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -2187,
            z: -4188,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 4067,
            z: -468,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 4555,
            z: 1933,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 4085,
            z: 2682,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1490,
            z: 2091,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1948,
            z: 212,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1932,
            z: 1372,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1153,
            z: -257,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1729,
            z: -1851,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 45,
            z: -1618,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
		{
            x: -3843,
            z: 1916,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
		{
            x: -4884,
            z: 1434,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
		{
            x: -503,
            z: 3309,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
		{
            x: -1853,
            z: 1378,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -889,
            z: 3366,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -540,
            z: 4140,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1595,
            z: 3844,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3931,
            z: 947,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1251,
            z: -1555,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 3382,
            z: -2356,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "black",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2019,
            z: -1643,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 2195,
            z: 963,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
    
        // ****************************************
        //
        // Portale
        //
        // ****************************************
        //tp 3999.5 96 1924.5
	    {
            x: 4000,
            z: 1925,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 5617,
            z: 1860,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -4987,
            z: -4840,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -3452,
            z: -3725,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1644,
            z: 5461,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 108,
            z: -7963,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1034,
            z: -8232,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 2677,
            z: -924,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1908,
            z: -4187,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 3430,
            z: -476,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 5926,
            z: 3315,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1050,
            z: 1627,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -1690,
            z: -3740,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: -3461,
            z: -2491,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 1406,
            z: -462,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 495,
            z: -397,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 350,
            z: -2445,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 877,
            z: 322,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 37,
            z: 872,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 292,
            z: -309,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 686,
            z: -435,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: -2221,
            z: 4973,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	{
            x: -947,
            z: -1131,
            image: ICON_UNKNOWN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine?",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1030,
            z: 229,
            image: ICON_PORTAL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portal",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1500,
            z: -1560,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1517,
            z: 748,
            image: ICON_MISC,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Portalruine",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Lighthouses
        //
        // ****************************************

        {
            x: 487,
            z: -853,
            image: ICON_LIGHTHOUSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Leuchtturm (Safehouse)",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Subway Stations
        //
        // ****************************************
        {
            x: 362,
            z: -252,
            image: ICON_SUBWAY,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "U-Bahn\nStation West",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET_2L,
            font: MARKER_FONT,
        },
        {
            x: 630,
            z: -429,
            image: ICON_SUBWAY,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "U-Bahn\nStation Nord",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET_2L,
            font: MARKER_FONT,
        },
        {
            x: 606,
            z: -319,
            image: ICON_SUBWAY,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "U-Bahn\nStation Ost",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET_2L,
            font: MARKER_FONT,
        },
        {
            x: 395,
            z: -286,
            image: ICON_SUBWAY,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "U-Bahn",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 469,
            z: -271,
            image: ICON_SUBWAY,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "U-Bahn\nStation Mitte",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET_2L,
            font: MARKER_FONT,
        },
        
        // ****************************************
        //
        // Railway Stations
        //
        // ****************************************    
        {
            x: 662,
            z: -308,
            image: ICON_TRAIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Bahnhof",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 775,
            z: 632,
            image: ICON_TRAIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Bahnhof",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 795,
            z: 1669,
            image: ICON_TRAIN,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Bahnhof",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },

        // ****************************************
        //
        // Unterkünfte
        //
        // ****************************************
        //tp 3991.5 95 1903.5
        {
            x: 3992,
            z: 1904,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 1054,
            z: -974,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1548,
            z: 4625,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
	    {
            x: 494,
            z: -407,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 350,
            z: -2455,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 752,
            z: 641,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 781,
            z: 1681,
            image: ICON_HOSTEL,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Unterkunft",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        

        // ****************************************
        //
        // Misc
        //
        // ****************************************
        //tp 704.5 79 -250.5
        {
            x: 705,
            z: -251,
            image: ICON_HORSE,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Mellys Reiterhof",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 703,
            z: -1011,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Zombiefalle",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: 435,
            z: -235,
            image: ICON_LIBRARY,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Zentral-\nbibliothek",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET_2L,
            font: MARKER_FONT,
        },
        {
            x: -1627,
            z: 4676,
            image: ICON_WATCHOUT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Stronghold Eingang",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1564,
            z: 4626,
            image: ICON_DEFAULT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Leitstein",
            textColor: "white",
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
        {
            x: -1725,
            z: 228,
            image: ICON_WATCHOUT,
            imageAnchor: [0.5, 1],
            imageScale: IMAGE_SCALE,
            text: "Sumpfhütte",
            textColor: "white", 
            offsetX: 0,
            offsetY: YOFFSET,
            font: MARKER_FONT,
        },
    ]
}
